backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pagina"
    label: "Contenido de la Página"
    files:
      - file: "index.html"
        label: "Página principal"
        name: "index"
        fields:
          - { label: "¿Quiénes somos?", name: "quienes_somos", widget: "text" }